---
abstract: 'Portage abstraction layer for perl'
author:
  - 'Christian Hartmann <ian@gentoo.org>'
  - 'Torsten Veller <tove@gentoo.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PortageXS
requires:
  Carp: 0
  DirHandle: 0
  Exporter: 0
  Scalar::Util: 0
  Shell::EnvImporter: 0
  Term::ANSIColor: 0
  overload: 0
  strict: 0
  warnings: 0
version: 0.2.11
